function updateVariables() {
  pageBasicElements.bodySection = GETDOMQUERY(".body_section");
  pageBasicElements.headsection = GETDOMQUERY(".head_section");
  pageBasicElements.headElementsLinks = GETDOMQUERY(".nav__link");
  pageBasicElements.headElementsItems = GETDOMQUERY(".nav__item");
  pageBasicElements.catagoriesCont = GETDOMQUERY(".categories");
  pageBasicElements.searchBar = GETDOMQUERY(".search_bar");
  pageBasicElements.searchBarInp = GETDOMQUERY("#search_input");
  pageBasicElements.searchBarBtn = GETDOMQUERY(".search_btn");
  pageBasicElements.searchBarImg = GETDOMQUERY(".search_img");
  pageBasicElements.headlineCont = GETDOMQUERY(".headline_cont");
  pageBasicElements.headline = GETDOMQUERY(".headlines");
  pageBasicElements.featureLeft = GETDOMQUERY(".left_feature_cover");
  pageBasicElements.featureRight = GETDOMQUERY(".right_feature_cover");
  pageBasicElements.featureCircle = GETDOMQUERY(".circle");
  pageBasicElements.featureFeatures = GETDOMQUERY(".featured_item");
  pageBasicElements.featureConts = GETDOMQUERY(".featured");
  pageBasicElements.featureDetails = GETDOMQUERY(".feature_detail");
  pageBasicElements.featureDetailsItems = GETDOMQUERY(".feature_details");
  pageBasicElements.featureCards = GETDOMQUERY(".feature_feature_card");
  pageBasicElements.featureInnerCont = GETDOMQUERY(".inner_cont");
  pageBasicElements.featurePageNo = GETDOMQUERY(".page_no");
}
